    - name: install java
      yum:
        name: java   
        state: present
        
    - name: download jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        
    - name: Install jenkins
      yum:
        name: jenkins
        state: present
        disable_gpg_check: yes
        
    - name: Ignore Default Password Promp
      shell: echo 2.0 >/var/lib/jenkins/jenkins.install.UpgradeWizard.state
      become_user: jenkins
    
    - name: Create init.d
      file:
        path: /var/lib/jenkins/init.groovy.d
        state: directory
      become_user: jenkins
      
    - name: Copy Init scripts      
      template:
        src: "{{item}}"
        dest: /var/lib/jenkins/init.groovy.d
      loop:
        - jenkins-plugins.groovy
        - jenkins-user.groovy
      become_user: jenkins
      
    - name: start jenkins
      systemd:
        name: jenkins
        state: restarted
        enabled: yes